name: tezda_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  riverpod_annotation: ^2.6.1
  flutter_dotenv: ^5.2.1
  logger: ^2.5.0
  freezed_annotation: ^2.4.4
  riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  flutter_screenutil: ^5.9.3
  overlay_support: ^2.1.0
  shared_preferences: ^2.3.4
  cached_network_image: ^3.4.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  auto_route: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0

  build_runner: ^2.4.6
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  hive_generator: ^2.0.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
    - .env_development
    - .env_local

# analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
